main: com.massivecraft.creativegates.CreativeGates
name: CreativeGates
version: 1.4
softdepend: [DimensionDoor, Multiverse-Core, MultiVerse, WorldManager, xcore]
permissions:
  creativegates.*:
    default: false
    children:
      creativegates.create: true
      creativegates.destroy: true
      creativegates.use: true
  creativegates.create:
    default: false
    description: create gates
  creativegates.destroy:
    default: false
    description: destroy gates
  creativegates.use:
    default: false
    description: use gates